# docker/docker-compose.yml
services:
  task-folder-setup:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - TZ=America/Los_Angeles
    env_file:
      - ../.env
    volumes:
      - ../config/config.yaml:/app/config/config.yaml:ro
      - ../media:/app/media
    command: python -u task_folder_setup.py

  task-sensor-log-handler:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - TZ=America/Los_Angeles
    env_file:
      - ../.env
    volumes:
      - ../config/config.yaml:/app/config/config.yaml:ro
      - ../media:/app/media
    command: python -u task_sensor_log_handler.py

  task-video-clip-fetcher:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - TZ=America/Los_Angeles
    env_file:
      - ../.env
    volumes:
      - ../config/config.yaml:/app/config/config.yaml:ro
      - ../media:/app/media
    command: python -u task_video_clip_fetcher.py

  task-object-classifier:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - TZ=America/Los_Angeles
    env_file:
      - ../.env
    volumes:
      - ../config/config.yaml:/app/config/config.yaml:ro
      - ../media:/app/media
      - ../models:/app/models
    command: python -u task_object_classifier.py

  task-report-publisher:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - TZ=America/Los_Angeles
    env_file:
      - ../.env
    volumes:
      - ../config/config.yaml:/app/config/config.yaml:ro
      - ../media:/app/media
      - ${PUBLISH_PATH}:/app/publish
    command: python -u task_report_publisher.py
